### ISSUE TITLE
how do you reference a flashlist ?

### ISSUE THREAD

**Issue by saimirg** [flexn-io/create#120]
Hi, how do you reference a flashlist ? 
We have navigation bar with tags/filters which effect a flashlist, and we want the flashlist to scroll to index 0 every time the tag/filter changes.

**Comment by aurimasmi** [comment]
Hi, does for data reloading? If it does it should go to the first item automatically

**Comment by saimirg** [comment]
Hi, it actually doesn't go. 
We have two flashlists on the screen, linked to a master-detail relationship (serial and episodes).

When you navigate through serials, episodes are automatically filtered below. Then you go to episodes and navigate through them. 
If you go back to Serials and chose another Serial and then go to Episodes again (that have changed now), focus is lost until you navigate left or right.

**Comment by aurimasmi** [comment]
That sounds like a legitimate bug, I'll try to reproduce it and fix it over the weekend. Thanks for sharing

**Comment by aurimasmi** [comment]
@saimirg managed to reproduce it. 
As a quick workaround before fix is made what you can do is set unique key `<FlashList key="uniqueKey" />` for Episodes FlashList once data there changing. In this way you will unmount in completely and focus works as expected.

**Comment by aurimasmi** [comment]
@saimirg try version `1.0.0-alpha.1`

**Comment by saimirg** [comment]
Sorry, dont want to jump to another issue, but how do i fix the "Cannot find module metro-cache" error ? 

The setup part runs fine.
<img width="764" alt="image" src="https://github.com/flexn-io/create/assets/11594998/05572cff-1282-4b18-8b62-f7f9e4e624ba">

But when i go to project folder and run: rnv run , it generates this error:
<img width="917" alt="image" src="https://github.com/flexn-io/create/assets/11594998/2415f3e9-f3a3-4b9c-9972-2192f1b2e622">

**Comment by saimirg** [comment]
Hi @aurimasmi, is there maybe another library i need to upgrade ? I keep getting the same error.

<img width="884" alt="image" src="https://github.com/flexn-io/create/assets/11594998/65b37efe-8e5f-4552-88bb-fbe2cbd8e1e0">

**Comment by aurimasmi** [comment]
So apparently there is issue in renative. If you would run `npx rnv -p platform_name` that should work. Could you try that?

**Comment by aurimasmi** [comment]
Can be tested in harness-app. Test ID `#DR1`
