### ISSUE TITLE
Altering build.gradle 

### ISSUE THREAD

**Issue by saimirg** [flexn-io/create#143]
Hi, i'm following below instructions on how to modify final build.gradle file by adding parameters on renative.json, but cant seem to make it work. Can you show me an example file on how to add them ?

<img width="1310" alt="image" src="https://github.com/flexn-io/create/assets/11594998/580ac2cc-da4d-436b-93fd-f9311fa8cbe5">

**Comment by mihaiblaga89** [comment]
@saimirg what exactly are you trying to add?

**Comment by saimirg** [comment]
I wanted to include google crashlytics. The default renative plugin is generating many errors, while using the crashlytics configuration from android studio works just fine. After configuration, android studio is adding the folling lines on gradle.

```
build.gradle (project-level)

    Add rules to include the Google Services Gradle plugin:
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
 
app/build.gradle

    Apply the Google Services Gradle plugin:
        apply plugin: 'com.google.gms.google-services'
        apply plugin: 'com.google.firebase.crashlytics'

    Add the library dependencies:
        implementation 'com.google.firebase:firebase-crashlytics:18.2.9'
        implementation 'com.google.firebase:firebase-analytics:20.1.2'
```

**Comment by mihaiblaga89** [comment]
The plugin should work, if you're getting errors maybe post them here to try to solve them. Otherwise you can have a look at how crashlytics is implemented in the plugins themselves. https://github.com/flexn-io/commonwealth/blob/main/packages/plugins/pluginTemplates/renative.plugins.json

**Comment by pauliusguzas** [comment]
@saimirg is this solved?
