### ISSUE TITLE
Carousel flickering when going left

### ISSUE THREAD

**Issue by saimirg** [flexn-io/create#144]
Hi, is there anyway to improve carousel flickering when going left ? Video is taken from an emulator, but on real/slower physical devices it not only flickers but also looses focus. 
This does not happen when going right. 

Also, if i go several pages on the right, when going left, after the flicker it alway takes you to the second page.

[flexn-create2.webm](https://github.com/flexn-io/create/assets/11594998/49ad2989-0e49-48ca-bad6-31f5fac38c78)

**Comment by pauliusguzas** [comment]
@saimirg thanks for reporting this, on what version of template was this?

**Comment by saimirg** [comment]
It was on the latest version 1.0.1. As far as i know it has been present on previous versions as well.

**Comment by pauliusguzas** [comment]
@saimirg yes this is a valid bug and will be looked into

**Comment by aurimasmi** [comment]
@saimirg It was fixed and released `1.1.0-alpha.4`
