### ISSUE TITLE
Feature request: Somehow send the onBlur event once you leave the Flashlist

### ISSUE THREAD

**Issue by ErnestasRa** [flexn-io/create#169]
## Current Issue

on TV designs, Spotlight only appears when one of the tiles is focused but disappears once the Carousel is reached at the top. So need to think of a way of how to implement this feature. 

 **Carousel - no spotlight**  
<img width="831" alt="image" src="https://github.com/flexn-io/create/assets/75485540/2de44a3e-08f7-484d-9c75-c5b72ada4132">

**Rails - spotlight**
<img width="826" alt="image" src="https://github.com/flexn-io/create/assets/75485540/c98c5cb6-31da-4e09-a6b0-323a77e40f4d">

**Comment by pauliusguzas** [comment]
@ErnestasRa how should this be tested?
