### ISSUE TITLE
[tvOS, ATV, fireTV] [Regression] Home screen focus issues on flexn/template

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/create#25]
rnv version: 0.36.1-canary.2
flexn template version: 0.16.0

- [ ] After clicking right when focused on "Try Me!" screen scrolls down
1. Be focused on "Try Me!"
2. Click right -> screen scrolls down

Expected:  nothing should happen

- [ ] After clicking down when focused on "Now Try Me!" focus is on twitter icon
1. Be focused on "Now Try Me!"
2. Click down -> focus is on twitter icon

Expected:  focus should be on chrome icon

**Comment by mihaiblaga89** [comment]
reopening as it was closed by a pr

**Comment by GabrieleKaceviciute** [comment]
Tested on tvOS and androidTV simulators - works as expected
