### ISSUE TITLE
Update Create docs + examples

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/create#35]
Current documentation is very old and doesn't represent reality it's needs to be updated + visual examples added

**Comment by GabrieleKaceviciute** [comment]
@aurimasmi what should be tested?

**Comment by mihaiblaga89** [comment]
@RosaryDarling can you give this PR a look? We discussed that a non-technical should have a look at it https://github.com/flexn-io/create/pull/115

**Comment by RosaryDarling** [comment]
Documentation pages for testing: 

- [ ] [Getting started](https://flexn-flexn-dev-flexn.vercel.app/docs/introduction)
- [ ] [Example app](https://flexn-flexn-dev-flexn.vercel.app/docs/tutorials/basics/example)
- [ ] [Components](https://flexn-flexn-dev-flexn.vercel.app/docs/introduction#)
- [ ] [ActivityIndicator](https://flexn-flexn-dev-flexn.vercel.app/docs/components/activity-indicator)
- [ ] [App](https://flexn-flexn-dev-flexn.vercel.app/docs/components/app)
- [ ] [ImageBackground](https://flexn-flexn-dev-flexn.vercel.app/docs/components/image-background)
- [ ] [Image](https://flexn-flexn-dev-flexn.vercel.app/docs/components/image)
- [ ] [Modal](https://flexn-flexn-dev-flexn.vercel.app/docs/components/modal)
- [ ] [Pressable](https://flexn-flexn-dev-flexn.vercel.app/docs/components/pressable)
- [ ] [FlashList](https://flexn-flexn-dev-flexn.vercel.app/docs/components/flash-list)
- [ ] [Screen](https://flexn-flexn-dev-flexn.vercel.app/docs/components/screen)
- [ ] [ScrollView](https://flexn-flexn-dev-flexn.vercel.app/docs/components/scrollview)
- [ ] [Switch](https://flexn-flexn-dev-flexn.vercel.app/docs/components/switch)
- [ ] [TextInput](https://flexn-flexn-dev-flexn.vercel.app/docs/components/text-input)
- [ ] [Text](https://flexn-flexn-dev-flexn.vercel.app/docs/components/text)
- [ ] [TouchableOpacity](https://flexn-flexn-dev-flexn.vercel.app/docs/components/touchable-opacity)
- [ ] [View](https://flexn-flexn-dev-flexn.vercel.app/docs/components/view)
- [ ] [Guides](https://flexn-flexn-dev-flexn.vercel.app/docs/introduction#)
- [ ] [Flexn Focus Manager](https://flexn-flexn-dev-flexn.vercel.app/docs/guides/focus-manager)

**Comment by RosaryDarling** [comment]
In this step it is a bit unclear - assuming this is only if I want to build a project which has TVs or does it have to be added to any project? 


![Image](https://github.com/flexn-io/create/assets/42945296/82e18733-44b8-40bf-afd2-c7a2693cc6d7)

**Comment by RosaryDarling** [comment]
In this step it would probably be a good  thing to mention that rnv has to be installed?  
Also I'm getting 'command not found: rnv' after trying to run this one - works with npx + [copied command]

![Image](https://github.com/flexn-io/create/assets/42945296/46c3a85f-9726-4ef8-9684-5883b5c96c5f)

**Comment by RosaryDarling** [comment]
Just to be sure - in App page, there's a link to react native docs - View component, so just want to double check if this is the exact page/component that should be used? 


![Image](https://github.com/flexn-io/create/assets/42945296/d86b30e3-f014-404c-a0b7-de6552c31a73)
