### ISSUE TITLE
[Regression] [macOS] All rows on carousels screen become narrow after scrolling down and back up again

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/create#38]
rnv version: 0.36.2-canary.4
flexn template version: 0.17.0

How to repro:
1. Open carousels screen
2. Scroll down -> some bottom rows are narrow
3. Scroll up -> all rows are narrow
<img width="755" alt="Screenshot 2022-09-09 at 14 25 18" src="https://user-images.githubusercontent.com/65670660/189340145-0576a466-d13c-4738-bea0-635c06f92ccb.png">

Expected:
Rows should be full width

**Comment by GabrieleKaceviciute** [comment]
not reproduced on v 0.21.3-rc.4
