### ISSUE TITLE
[AndroidTV, fireTV] When holding 'down' button in Carousels screen focus jumps on @flexn/template

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/create#42]
rnv version: 0.36.2-canary.4
flexn template version: 0.17.0

How to repro:
1. Navigate to Carousel screen
2. Hold 'down' button on remote or in keyboard
3. Screen scrolls down a bit and then jumps to the top

https://user-images.githubusercontent.com/65670660/189882268-2f18d4da-414a-44d4-a9de-8937dde766b5.mov

Expected: Scrolling is smooth without any jumping

**Comment by GabrieleKaceviciute** [comment]
not reproduced on v 0.21.3-rc.4
