### ISSUE TITLE
flexn/template e2e tests fail on tvOS

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/create#50]
garybox and flexn/template versions: 0.17.0-alpha.10

For whatever reason  `await FlexnRunner.expectToBeDisplayedById('template-carousels-screen-container');` returns not displayed whereas in the second test on the same screen it returns displayed
<img width="594" alt="Screenshot 2022-10-07 at 13 06 47" src="https://user-images.githubusercontent.com/65670660/194529558-68d54502-e0b9-46fb-8675-5ef76cd79b0f.png">

**Comment by pauliusguzas** [comment]
AndroidTV is also failing now

**Comment by RosaryDarling** [comment]
closing as no longer relevant with newer studio version, will need to retest everything

**Comment by pauliusguzas** [comment]
@RosaryDarling this is not about studio

**Comment by pauliusguzas** [comment]
Not reproduced
