### ISSUE TITLE
React native video 

### ISSUE THREAD

**Issue by henrimagoware** [flexn-io/create#76]
Hello ,
I am building a TV app based on Flexn framework  , one of the things I am trying to do is installing a library called react-native-video to make a stream playing . When i am trying  to do the configurations for Android  TV platform , after I set them manually and try it to run the changes i added set to defaults . I have upload a picture of the configurations that i want to be add and to be saved . I think that after the configurations are made the video would play .

Can anyone  help with any  solution ?
Thank you . 

![image](https://user-images.githubusercontent.com/131362712/233362438-5c56d453-700c-4476-9876-3f82a942085e.png)

**Comment by mihaiblaga89** [comment]
How did you add the plugin? Manually? If so, please try to undo everything you did and try it with `rnv plugin add react-native-video`. This should add it and also configure everything that needs configured on the native side. 

If you still want to do it manually all you need to do is add this in your `renative.json` `plugins` section
```
"react-native-video": "source:rnv",
```

An even more advanced example would be adding the next section in plugins instead of the `source:rnv`, which would allow you to have even more control

```
"react-native-video": {
            "version": "5.0.2",
            "ios": {
                "podName": "react-native-video"
            },
            "tvos": {
                "podName": "react-native-video"
            },
            "android": {
                "package": "com.brentvatne.react.ReactVideoPackage"
            },
            "androidtv": {
                "package": "com.brentvatne.react.ReactVideoPackage"
            },
            "firetv": {
                "package": "com.brentvatne.react.ReactVideoPackage"
            },
            "webpack": {
                "modulePaths": true
            }
        },
```

**Comment by henrimagoware** [comment]
Hello ,
I added the followed instructions as you said and it came with an error as in the photo below .

![image](https://user-images.githubusercontent.com/131362712/234012539-53aa2eda-f6f8-4525-83fd-05b719466bd3.png)
![image](https://user-images.githubusercontent.com/131362712/234012674-7c9aabf9-f2b4-4ab9-a08c-c5ff12423db3.png)

Do you suggest any solution of this problem .
My node js version is 16.16.0.

Thank you !

**Comment by mihaiblaga89** [comment]
@henrimagoware please use "source:flexn" instead of "source:rnv" in your `renative.json`. Also make sure you have `@flexn/plugins` in your `devDepencencies`.
```
"plugins": {
    "react-native-video": "source:flexn"
},
```
This should fix the issue.

**Comment by mihaiblaga89** [comment]
closing this, feel free to reopen if needed
