### ISSUE TITLE
onHoverIn missing from types in Pressable

### ISSUE THREAD

**Issue by pavjacko** [flexn-io/create#78]
//@ts-ignore Flexn SDK does not have this prop?
            onHoverIn={() => {
                setIsHover(true);
                tSetState('hover');
            }}

**Comment by locksten** [comment]
Workaround in prd-ost-flosky:
https://github.com/flexn-seals/prd-ost-flosky/blob/802f8b54a396d94c144af83b398d67d75156e7f6/packages/sdk-flosky/typings/react-native.d.ts#L42

**Comment by aurimasmi** [comment]
@locksten @pavjacko how did you made this workaround? When our RN version does not even support onHoverIn https://reactnative.dev/docs/0.67/pressable

**Comment by locksten** [comment]
@aurimasmi I didn't write that code, but I'm pretty sure that `react-native-web` supported those props earlier than `react-native`.
